Ստորև գրված առաջադրանքները կատարելու վերջնաժամկետը **07.09.2020 16:00** է։ Առաջադրանքները կատարելուց հետո, պետք է 

1. ներբեռնեք այս ֆայլը ձեր համակարգիչ (`File` $\to$ `Download .ipynb`)
2. վերնագրին ավելացնեք ձեր անուն, ազգանունը լատինատառ, օրինակ՝ *HW4_Numpy_NshanPotikyan.ipynb* ֆորմատով
3. ուղարկեք ֆայլը **nshanp@fast.foundation** հասցեին` նամակի թեմա (subject) դաշտում գրելով **HW4**

**Ուշադրություն**․ 
1. Վերոնշյալ պայմաններին չբավարարելու դեպքում ձեր աշխատանքը չի գնահատվի։
2. Յուրաքանչյուր վարժության կոդը գրելուց հետո աշխատացրեք անմիջապես ներքևի վանդակը, որի մեջ հիմնականում գրված են **assert**֊ով հրամաններ։ Եթե այդ վանդակը աշխատացնելիս ստանում եք `AssertionError`, ապա ինչ֊որ բան սխալ եք արել և եթե ոչինչ չի վերադարձվում, ապա մեծ հավանականությամբ ճիշտ եք լուծել վարժությունը։ 
3. Ոչինչ մի՛ փոխեք  այն վանդակներում, որտեղ գրված է "Do not modify this cell" գրառումը
4. Ձեր աշխատանքը գնահատելիս առկա ստուգումներից բացի կարող է կատարվեն այլ ստուգումներ։  



In [2]:
import numpy as np

Using libraries other than numpy is **prohibited**.

Բացի numpy-ից այլ գրադարանների օգտագործումն **արգելված է**։

**Error handling**

>1․ Եթե որպես ֆունկցիայի պարամետր ստանում եք numpy զանգված (վեկտոր կամ մատրից), և այն չի համապատասխանում խնդրում նշված չափին (dimensions) կամ չափերի անհամաձայնություններ կան, ապա վերադարցրեք(return) **"DimensionError"** տեքստը

>2․ Եթե որպես ֆունկցիայի պարամետր ստանում եք 2D numpy զանգված (մատրից), և այն հակադարձելի(invertable) չէ, հակառակ խնդրի պահանջի, ապա վերադարցրեք(return) **"NotInvertableError"** տեքստը

# Problems

Problem 1. Compute the euclidean distance between two arrays. 


> Հաշվիր 2 զանգվածների Էվկլիդյան հեռավորությունը։


```
a, b = np.array([1, 2]), np.array([1, 3])
print(dist(a, b))
>>1
```


In [14]:
def dist(a, b):
  evk = np.linalg.norm(np.subtract(a,b))
  return evk
a = [1,2,3]
b = [9,8,-3]
print(dist(a,b))

11.661903789690601


In [13]:
# Do not modify this cell
a, b = np.array([1, 1]), np.array([1, 3])
assert dist(a, b) == 2

a, b = np.array([-10, 1.5]), np.array([0.9, 3.6])
assert round(dist(a, b), 2) == 11.1

a, b = np.array([1, 1, 1]), np.array([0, -1, 3])
assert dist(a, b) == 3

a, b = np.array([1, 0, -999]), np.array([1, 3])
assert dist(a, b) == "DimensionError"

a, b = np.array([10, -1, 9, 1, 2.98, -0.14]), np.array([0, -1, 3.14, np.pi, 99, np.e])
assert round(dist(a, b), 2) == 96.78

ValueError: ignored

Problem 2. Normalize an array so the values range exactly between 0 and 1․

> Նորմավորիր զանգվածը այնպես, որ արժեքները լինեն 0-ից 1 միջակայքում։

```
a = np.array([1,2,3,4])
print(rescale(a))
>>[0, 0.3333333, 0.66666667, 1]
```



In [15]:
def rescale(a):
  norm =np.linalg.norm(a)
  return a/norm
a= np.array([12,3,4,5])
print(rescale(a))

[0.86154979 0.21538745 0.28718326 0.35897908]


In [ ]:
# Do not modify this cell
assert np.all(rescale(np.array([1, 2, 3, 4])) == [0, 1/3, 2/3, 1])
assert np.all(rescale(np.array([0, 1])) == [0, 1])
assert np.all(rescale(np.array([0, 10])) == [0, 1])
assert np.all(rescale(np.array([1, 2, 4])) == [0, 1/3, 1])

Problem 3. Find the position of missing values in 1D numpy array.

> Գտիր բացակայող արժեքների տեղերը 1D numpy զանգվածում:


```
a = np.array([np.nan, 1, 2])
print(find(a))
>>[0]
```



In [3]:
def find(a):
  l = np.isnan(a)
  print(l)
  n = []
  for i in range(len(l)):
    if l[i] == True:
      n.append(i)
  return n
a = np.array([12,np.nan,3,np.nan])
print(find(a))

[False  True False  True]
[1, 3]


In [ ]:
# Do not modify this cell
assert np.all(find(np.array([np.nan, 1, 2, np.nan])) == [0, 3])
assert np.all(find(np.array([np.nan, np.nan])) == [0, 1])
assert np.all(find(np.array([np.e, 1, 2, 99])) == [])
assert np.all(find(np.array([np.e])) == [])
assert np.all(find(np.array([])) == [])

Problem 4. Given a numpy array 'a' that contains n elements, denote by b the set of its unique values ​​in ascending order, denote by m the size of array b. You need to create a numpy array with dimensions $n \times m$, in each row of which there must be a value of 1 in case it is equal to the value of the given index of array b, in other places it must be 0.

> Տրված է numpy զանգված 'a', որը պարունակում է n էլեմենտ, b-ով նշանակենք նրա ունիկալ արժեքների (արժեքներն առանց կրկնության) զանգվածը ըստ աճման կարգի, m-ով նշանակենք b զանգվածի չափը: Հարկավոր է ստեղծել numpy զանգված $n \times m$ չափերով, որի i-րդ տողի j-րդ սյան տեղում պետք է գրված լինի 1 այն դեպքում, երբ a-ի i-րդ անդամը հավասար է b֊ի j-րդ արժեքին, իսկ մնացած տեղերում պետք է լինեն 0֊ներ։


```
a = np.array([1, 1, 2, 3, 2, 4])
# b = np.array([1, 2, 3, 4])
print(convert(a))
>>[[1, 0, 0, 0],
  [1, 0, 0, 0],
  [0, 1, 0, 0],
  [0, 0, 1, 0],
  [0, 1, 0, 0],
  [0, 0, 0, 1]]
```



In [36]:
def convert(a):
  n =len(a)
  b = np.unique(a)
  b.sort
  m = len(b)
  l = []
  for i in range(n):
    for j in range(m):
      if a[i] == b[j]:
        l.append(1)
      else:
        l.append(0)
  a = np.array(l)
  return a.reshape(n,m)
a = [1,1,2,3,2,4]
print(convert(a))


[[1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]]


In [30]:
x= [1,2,2]
a= np.unique(x)
a.osrt

[1 2]


In [ ]:
# Do not modify this cell
assert np.all(convert(np.array([0, 0, 2, 3, 2, 4])) ==
              [[1, 0, 0, 0],
               [1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 1, 0],
               [0, 1, 0, 0],
               [0, 0, 0, 1]])

assert np.all(convert(np.array([-np.pi, 9])) ==
              [[1, 0],
               [0, 1]])

assert np.all(convert(np.array([-1, 1, 9, 10])) ==
              [[1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 1, 0],
               [0, 0, 0, 1]])

assert np.all(convert(np.array([np.sqrt(2), np.sqrt(2), np.sqrt(2)])) ==
              [[1],
               [1],
               [1]])

Problem 5. Given a 2D numpy array 'a' of sizes $n \times m$. You need to pad the matrix with 0s so that the dimensions of the matrix become  $(n+2n_1) \times (m+2m_1)$
>Տրված է 2D numpy զանգված 'a' $n \times m$ չափերի, Հարկավոր է կողքերից հավասարաչափ 0-ներ ավելացնել այնպես, որ զանգվածի չափերը դառնան $(n+2n_1) \times (m+2m_1)$

```
a = np.array([[1, 1], [1, 1]])
n1 = 1
m1 = 2
print(padding(a, n1, m1))
>>[[0, 0, 0, 0, 0, 0], 
  [0, 0, 1, 1, 0, 0],
  [0, 0, 1, 1, 0, 0],
  [0, 0, 0, 0, 0, 0]]
```



In [21]:
def padding(a, n1, m1):
    ap = np.pad(a,((n1,n1),(m1,m1)),"constant",constant_values = 0)
    return ap
a = np.array([[1, 1], [1, 1]])
n1 = 1
m1 = 2
print(a)
print(padding(a,n1,m1))

  

[[1 1]
 [1 1]]
[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


In [16]:
a = np.array([[1, 1,2], [1, 1,54]])
print(np.dim(a))
a

AttributeError: module 'numpy' has no attribute 'dim'

In [ ]:
# Do not modify this cell
assert np.all(padding(np.array([[1, 1], [1, 1]]), 1, 2) ==
              [[0, 0, 0, 0, 0, 0],
               [0, 0, 1, 1, 0, 0],
               [0, 0, 1, 1, 0, 0],
               [0, 0, 0, 0, 0, 0]])

assert np.all(padding(np.array([[1, 2], [1, 1]]), 0, 2) ==
              [[0, 0, 1, 2, 0, 0],
               [0, 0, 1, 1, 0, 0]])

assert np.all(padding(np.array([[9]]), 2, 2) ==
              [[0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 9, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0]])

Problem 6. Given a 2D numpy array 'a' of sizes $n \times m$ and a 1D numpy array 'b' of size m. You need to find the distance(Euclidean) of the 'b' vector from the rows of the 'a' matrix. Fill the results in the numpy array.
Extra points for writing without a loop.
>Տրված է 2D numpy զանգված 'a' $n \times m$ չափերի և m չափանի 1D numpy զանգված 'b' անունով։ Հարկավոր է գտնել 'b' վեկտորի Էվկլիդյան հեռավորությունը 'a' մատրիցի տողերից և արդյունքները լցնել numpy զանգվածի մեջ։ Խնդիրը Broadcasting֊ի միջոցով լուծողները կստանան լրացուցիչ միավոր։

```
a = np.array([[1, 1],
              [0, 1],
              [1, 3],
              [4, 5]])
b = np.array([1, 1])
print(dist(a, b))
>>[0,1,2,5]
```



In [ ]:
def dist(a, b):
  #your code here

In [ ]:
# Do not modify this cell
a, b = np.array([[1, 1],
                 [0, 1],
                 [1, 3],
                 [4, 5]]), np.array([1, 1])
assert np.all(dist(a, b) == [0., 1., 2., 5.])

a, b = np.array([[np.e, 0, 1.5],
                 [0, 1, -10]]), np.array([1, 3.14, 0])
assert np.all(np.round(dist(a, b)) == [4, 10])

a, b = np.array([[1, 1],
                 [0, 1]]), np.array([1, 1, 1])
assert dist(a, b) == "DimensionError"

Problem 7. Given 2D numpy arrays 'a' and 'b' of sizes $m \times n$ and $k \times k$ respectively (k <= n, k <= m), 2 integers 'stride' and 'padding' and 'f' function. You need to 
  1. first pad 'a' matrix with 0s on each side, 
  2. then move 'b'  over 'a' with stride 'stride', then multiply their elements by the corresponding 'b' elements, 
  3. add the resulting k * k numbers 
  4. apply the 'f' function to the result 
  5. and place them in the new matrix.

  Տրված է 2D numpy զանգվածներ 'a' և 'b' համապատասխանաբար $m \times n$ և $k \times k$ չափերի (k<=n, k<=m), 2 ամբողջ թվեր 'stride' և 'padding' ու 'f' ֆունկցիա։ Հարկավոր է

  1․ 'a' մատրիցին 'padding' չափով 0֊ներ ավելացնել յուրաքանչյուր կողմից,

  2․ ապա 'b'֊ն 'stride' քայլով "շարժել" 'a'֊ի վրայով և 'a'֊ի համապատասխան էլեմենտները բազմապատկել 'b'-ի համապատասխան էլեմենտներով,

  3․ ստացված k*k հատ թվերը գումարել,

  4․ արդյունքի վրա կիրառել 'f' ֆունկցիան

  5․ և տեղադրել նոր մատրիցում։

```
a = np.array([[1, 1, 2],
              [0, 1, 3],
              [1, 3, 0],
              [4, 5, 2]])
b = np.array([[1, 0],
              [0, 1]])

stride = 1
padding = 0
f = lambda x: x**2
print(conv(a, b, stride, padding, f))
>>[[4, 16],
  [9, 1],
  [36, 25]]
```
![ConvUrl](https://miro.medium.com/max/2340/1*Fw-ehcNBR9byHtho-Rxbtw.gif "conv")


In [ ]:
def conv(a, b, stride, padding, f):
  #your code here

In [ ]:
# Do not modify this cell
a = np.array([[1, 1, 2],
              [0, 1, 3],
              [1, 3, 0]])
b = np.array([[1, 0],
              [0, 1]])
f = lambda x: x**2
assert np.all(conv(a, b, 1, 0, f) ==
              [[4., 16.],
               [9.,  1.]])

a = np.array([[1, 1, 2],
              [0, 1, 3],
              [1, 3, 0],
              [-10, -3, 0]])
b = np.arange(9).reshape(3, 3)
f = lambda x:0 if x<0 else x
assert np.all(conv(a, b, 1, 0, f) ==
              [[51.],
               [0.]])

b = np.arange(6).reshape(2, 3)
assert conv(a, b, 1, 0, f) == "DimensionError"

Problem 8. Given a 2D numpy array 'a' of sizes $m \times n$ whose each line is labeled with 0 or 1 numbers and a  vector  (of size n) which is not labeled. You need to find the appropriate label for 'b'. In the 'a' matrix, find the line closest to 'b' (according to the Euclidean distance) and label 'b' with the label of that line.
>Տրված է $m \times n$ չափանի 2D numpy զանգված՝ 'a', որի յուրաքանչյուր տող պիտակավորված (label) է 0 կամ 1 թվերով և 'b' վեկտոր (n չափի) որը պիտակավորված չէ։ Հարկավոր է գտնել 'b'֊ի համապատասխան պիտակը (label)՝ գտնելով 'a' մատրիցում 'b'ին ամենամոտ  տողը (ըստ Էվկլիդյան հեռավորության) և 'b'֊ն պիտակավորեք այդ տողի պիտակով։

```
a = np.array([[1, -2],
              [2, 5],
              [-3, -10],
              [3, 2],
              [3, 2],
              [0, 1]])
labels = np.array([0,1,0,1,1,0])
b = np.array([10,10])
print(predict_label(a,labels,b))
>>1
```



In [ ]:
def predict_label(a,labels,b):
  #your code here

In [ ]:
# Do not modify this cell
a = np.array([[1, -2],
              [2, 5],
              [-3, -10],
              [3, 2],
              [3, 2],
              [0, 1]])
labels = np.array([0, 1, 0, 1, 1, 0])

assert predict_label(a, labels, np.array([10, 10])) == 1
assert predict_label(a, labels, np.array([10, -10])) == 0
assert predict_label(a, labels, np.array([10, -1])) == 1
assert predict_label(a, labels, np.array([1, 1, 0])) == "DimensionError"

a = np.array([[0, 1, -2],
              [2, 1, 5],
              [-3, 3.5, -10],
              [3, 2, 9],
              [3, -2, 9]])
labels = np.array([0, 1, 0, 1, 1])
assert predict_label(a, labels, np.array([1])) == "DimensionError"
assert predict_label(a, labels, np.array([1, 1, 0])) == 0
assert predict_label(a, labels, np.array([1, 1, 10])) == 1

Problem 9. Given a 2D numpy array 'a' of sizes $m \times n$ with missing elements (NAN) and a string 'mode' $\in$ {"mean","min","max"}. You need to write the {"mean","min","max"} ('mode') of the corresponding column instead of the missing elements.
>Տրված է 2D numpy զանգված 'a' $m \times n$ չափերի, որն ունի բացակայող էլեմենտներ (NAN) ու տեքստային փոփոխական 'mode' $\in$ {"mean","min","max"}։ Հարկավոր է 'a' մատրիցի բացակայող էլեմենտների փոխարեն գրել համապատասխան սյան {միջինը, մինիմումը, մաքսիմումը} ըստ 'mode' փոփոխականի։

```
a = np.array([[np.nan, 200, 10],
              [2, 110, np.nan],
              [0, 120, 11],
              [0, 400, np.nan],
              [1, np.nan, 9]])
mode = "mean"
print(fill(a, mode))
>>[[  0.75 200.    10.  ]
 [  2.   110.    10.  ]
 [  0.   120.    11.  ]
 [  0.   400.    10.  ]
 [  1.   207.5    9.  ]]
```



In [ ]:
def fill(a, mode):
  #your code here

In [ ]:
# Do not modify this cell
a = np.array([[np.nan, 200, 10],
              [2, 110, np.nan],
              [0, 120, 11],
              [0, 400, np.nan],
              [1, np.nan, 9]])

assert np.all(fill(a, "mean") ==
              [[0.75, 200.,  10.],
               [2., 110.,  10.],
               [0., 120.,  11.],
               [0., 400.,  10.],
               [1., 207.5,   9.]])

assert np.all(fill(a, "min") ==
              [[0., 200.,  10.],
               [2., 110.,   9.],
               [0., 120.,  11.],
               [0., 400.,   9.],
               [1., 110.,   9.]])

assert np.all(fill(a, "max") ==
              [[2., 200.,  10.],
               [2., 110.,  11.],
               [0., 120.,  11.],
               [0., 400.,  11.],
               [1., 400.,   9.]])

Problem 11. Given a numpy matrix 'A' of sizes $n \times n$ and a numpy vector 'b' of size n. You need to calculate the value of the expression
$${1\over2}\mathbf{b}^TA^{-1}\mathbf{b}*\prod_{i}\lambda_i ;\text{ where  $\lambda_i$  are eigenvalues of }A$$

>Տրված է numpy մատրից 'A' $n \times n$ չափերի և numpy վեկտոր 'b' n չափի։ Հարկավոր է հաշվել հետևյալ արտահայտության արժեքը։
$${1\over2}\mathbf{b}^TA^{-1}\mathbf{b}*\prod_{i}\lambda_i ; \text{ որտեղ $\lambda_i$֊երը A-ի սեփական արժեքներն են}$$

```
a = np.array([[1, 1, 2],
              [0, 1, 3],
              [1, 3, 0]])
b = np.array([1, 0, 1])
print(calc(a, b))
>>-4.000000000000002
```


In [ ]:
def calc(a, b):
  #your code here

In [ ]:
# Do not modify this cell
a = np.array([[1, 1, 2],
              [0, 1, 3],
              [1, 3, 0]])
b = np.array([1, 0, 1])
assert round(calc(a, b)) == -4

a = np.array([[1, 1, 2],
              [0, 1, 3],
              [1, 3, 0]])
b = np.array([1, 0, 1, 1])
assert calc(a, b) == "DimensionError"

a = np.array([[1, 1, 2],
              [1, 1, 3],
              [3, 3, 0]])
b = np.array([1, 0, 1])
assert calc(a, b) == "NotInvertableError"

a = np.array([[10, 1],
              [-1, 1]])
b = np.array([1, 1])
assert round(calc(a, b), 2) == 5.5

Problem 12. Given a numpy matrix 'a' of sizes $m \times n$ and a number 'k' in range [0,1]. The rows of 'a' should be randomly divided into parts in the ratio k:(1-k). (If the parts are not integers, round them)
>Տրված է $m \times n$ չափերի numpy մատրից 'a'  և [0,1] միջակայքի 'k' թիվ ։ Հարկավոր է 'a'ի տողերը պատահականորեն բաժանել k։(1-k) հարաբերությամբ մասերի։ (եթե մասերը ամբողջ թվեր չեն, ապա կլորացրեք)

```
a = np.array([[1, 1, 2],
              [0, 108, 3],
              [1, 3, 65],
              [50, 35, 5],
              [5, 83, 110],
              [98, 99, 10],
              [8, 9, 103],
              [9, 23, 15]])
k = 0.25
print(rand_split(a, k))
>>(array([[  1,   3,  65],
       [  8,   9, 103]]),
   array([[ 98,  99,  10],
       [ 50,  35,   5],
       [  1,   1,   2],
       [  5,  83, 110],
       [  0, 108,   3],
       [  9,  23,  15]]))
```


In [ ]:
def rand_split(a, k):
  #your code here

In [ ]:
# Do not modify this cell
a = np.array([[1, 1, 2],
              [0, 108, 3],
              [1, 3, 65],
              [50, 35, 5],
              [5, 83, 110],
              [98, 99, 10],
              [8, 9, 103],
              [9, 23, 15]])
k = 0.25

for _ in range(100):
    x1, x2 = rand_split(a, k)
    assert len(x1) == 2 and len(x2) == 6
    assert np.all(np.sum(x2 != x1[0], axis=1))
    assert np.all(np.sum(x2 != x1[1], axis=1))

Problem 13. Given a numpy matrix 'a' of sizes $m \times n$ and the numbers 'k' and 'q' in the range [0,1]. You need to randomly select the 'k' part of the rows of 'a' (can be repeated) and the 'q' part of their columns (should not be repeated).
>Տրված է numpy մատրից 'a' $m \times n$ չափերի և [0,1] միջակայքի 'k' և 'q' թվեր։ Հարկավոր է պատահականորեն ընտրել 'a'ի տողերի 'k' մասը (կարող են կրկնվել) և դրանց սյուների 'q' մասը (չպետք է կրկնվեն)։

```
a = np.array([[1, 1, 2],
              [0, 108, 3],
              [1, 3, 65],
              [50, 35, 5],
              [5, 83, 110],
              [98, 99, 10],
              [8, 9, 103],
              [9, 23, 15]])
k = 0.25
q = 0.6
print(rand_rows_cols(a, k, q))
>>[[83, 110],
  [3, 65]]
```


In [ ]:
def rand_rows_cols(a, k, q):
  #your code here

In [ ]:
# Do not modify this cell
a = np.array([[1, 1, 2],
              [0, 108, 3],
              [1, 3, 65],
              [50, 35, 5],
              [5, 83, 110],
              [98, 99, 10],
              [8, 9, 103],
              [9, 23, 15]])
k = 0.25
q = 0.6

for _ in range(100):
    x1 = rand_rows_cols(a, k, q)
    assert x1.shape == (2, 2)

Problem 14. Given a numpy matrix 'W' of sizes $m \times n$, numpy vectors 'a' and 'b' of size n and m respectively and function 'f'. You need to calculate the value of the expression $f(W\mathbf{a}+\mathbf{b})$.
>Տրված է $m \times n$ չափերի numpy մատրից 'W', numpy վեկտորներ 'a' ու 'b' համապատասխանաբար n ու m չափերի և 'f' ֆունկցիա։ Հարկավոր է հաշվել $f(W\mathbf{a}+\mathbf{b})$ արտահայտության արժեքը։

```
w = np.array([[1, 1, 2],
              [0, 1, 3]])
a = np.array([3, 0, 1])
b = np.array([1, -2])
f = lambda x: x**2
print(dense_layer(w, a, b, f))
>>[36, 1]
```


In [ ]:
def dense_layer(w, a, b, f):
  #your code here

In [ ]:
# Do not modify this cell
w = np.array([[1, 1, -2],
              [0, -1, 3]])
a = np.array([3, 10, 1])
b = np.array([0, -2])
f = lambda x: x**2
assert np.all(dense_layer(w, a, b, f) == [121,  81])

f = lambda x: x
assert np.all(dense_layer(w, a, b, f) == [11,  -9])


w = np.array([[1, 1],
              [0, -1]])
assert dense_layer(w, a, b, f) == "DimensionError"

Problem 15. Given a numpy matrix 'a' of sizes $m \times n$. You need to find the rows of 'a' whose sum of elements is in the range [100,200).
>Տրված է $m \times n$ չափերի numpy մատրից 'a'։ Հարկավոր է գտնել 'a'-ի այն տողերը՝ որոնց էլեմենտների գումարը գտնվում է [100,200) միջակայքում։

```
a = np.array([[1, 1, 2],
              [0, 108, 3],
              [1, 3, 65],
              [50, 35, 5],
              [5, 83, 110],
              [98, 99, 10],
              [8, 9, 103],
              [9, 23, 15]])
print(between_100_200(a))
>[[0, 108, 3],
  [5, 83, 110],
  [8, 9, 103]]
```


In [ ]:
def between_100_200(a):
  #your code here

In [ ]:
# Do not modify this cell
a = np.array([[1, 1, 2],
              [0, 108, 3],
              [1, 3, 65],
              [50, 35, 5],
              [5, 83, 110],
              [98, 99, 10],
              [8, 9, 103],
              [9, 23, 15]])
assert np.all(between_100_200(a) ==
              [[0, 108,   3],
               [5,  83, 110],
               [8,   9, 103]])

a = np.array([[1, 1, 2],
              [0, -108, 3],
              [1, 3, 65],
              [50, 35, 5]])
assert len(between_100_200(a)) == 0

Problem 16. Get the L in the Cholesky decomposition of x.

> Գտիր x-ի Չոլեսկու դեկոմպոզիցիայի L-ը:


```
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
print(Cholesky(x))
>>[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]
```



In [ ]:
def Cholesky(x):
  #your code here

In [ ]:
# Do not modify this cell
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])
assert np.all(Cholesky(x) ==
              [[2.,  0.,  0.],
               [6.,  1.,  0.],
               [-8.,  5.,  3.]])

Problem 17. Write a function to return a 2d array of given size with 1s on the border and 0s inside. 

Գրել ֆունկցիա, որը կվերադարձնի տրված չափանի երկչափ numpy array (քառակուսի մատրից), որտեղ եզրերում կլինեն 1-եր, իսկ ներսում՝ 0-ներ։  



In [ ]:
def zero_one(x):
  #your code here

In [ ]:
assert np.array_equal(zero_one(3), np.array([[1., 1., 1.],
                                            [1., 0., 1.],
                                            [1., 1., 1.]]))
assert np.array_equal(zero_one(4), np.array([[1., 1., 1., 1],
                                            [1., 0., 0., 1],
                                            [1., 0., 0., 1],
                                            [1., 1., 1., 1]]))

Problem 18. Given 2D numpy arrays 'a' and 'b' of sizes  $n\times m$ and $k\times m$ respectively and one natural number 'p'. You need to find the distance(Euclidean) of the rows of the matrices 'a' and 'b'. Fill the results in the $k \times n$ matrix. Calculate the distance with the following formula
$$D(\mathbf{x},\mathbf{y})=\left(\sum_{i=1}^m{ |x_i-y_i|^p }\right)^{1/p};\ \mathbf{x},\mathbf{y}\in R ^m$$ 
(try to prove that this is a distance).
Extra points for writing without a loop.
>Տրված է 2D numpy զանգվածներ 'a' և 'b' համապատասխանաբար $n\times m$ և $k\times m$ չափերի և 1 բնական թիվ 'p'։ Հարկավոր է գտնել 'a' և 'b' մատրիցների տողերի հեռավորությունները և արդյունքները լցնել $k \times n$ մատրիցի մեջ։ Հեռավորությունը հաշվել հետևյալ բանաձևով
$$D(\mathbf{x},\mathbf{y})=\left(\sum_{i=1}^m{ |x_i-y_i|^p }\right)^{1/p};\ \mathbf{x},\mathbf{y}\in R^m$$(փորձեք ապացուցել, որ սա հեռավորություն է):
Խնդիրը Broadcasting֊ի միջոցով լուծողները կստանան լրացուցիչ միավոր։

```
a = np.array([[1, 1],
              [0, 1],
              [1, 3],
              [4, 5]])
b = np.array([[1, 1],
              [-1, 0]])
p=2
print(dist_mat(a, b, p))
>[[0.         1.         2.         5.        ]
 [2.23606798 1.41421356 3.60555128 7.07106781]]
```



In [ ]:
def dist_mat(a, b, p):
    if a.shape[1] != b.shape[1]:
        return "DimensionError"
    return np.sum(np.abs(a-b[:, np.newaxis])**p, axis=2)**(1/p)

# Do not modify this cell
a = np.array([[-15, 1.5],
              [10, 7],
              [1, 35],
              [4, -5]])

b = np.array([[1, 16],
              [-1, 0],
              [-1, 50]])
p = 3

dist_mat(a, b, p)

In [ ]:
# Do not modify this cell
a = np.array([[-15, 1.5],
              [10, 7],
              [1, 35],
              [4, -5]])
b = np.array([[1, 16],
              [-1, 0],
              [-1, 50]])
p = 3
assert np.all(np.round(dist_mat(a, b, p)) ==
              [[19, 11, 19, 21],
               [14, 12, 35,  6],
               [49, 43, 15, 55]])

a = np.array([[-15, 1.5],
              [10, 7],
              [1, 35],
              [4, -5]])
b = np.array([[1, 16, 1],
              [-1, 0, 1]])
p = 3
assert dist_mat(a, b, p) == "DimensionError"

[[[ 1 16]]

 [[-1  0]]

 [[-1 50]]]


Problem 19. Այս խնդիրը լուծելու համար պետք է գրանցվել codesignal.com կայքում։ Այնուհետև պետք է անցնել [այս հղումով](https://app.codesignal.com/challenge/7BfPFxPyvvcJCzBuq) և լուծել խնդիրը։ Լուծումը ստուգելու համար պետք է ընտրեք "RUN SAMPLE TESTS" տարբերակը, իսկ հանձնելու համար՝ "SUBMIT" տարբերակը։ 